name: Manual Questa self-hosted basic UVM Test

on:
  workflow_dispatch:

jobs:
  uvm-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python virtual environment
        run: |
          python3.12 -m venv venv_cv32e20-dv/
          source venv_cv32e20-dv/bin/activate
          pip install --upgrade pip
          pip install -r bin/requirements.txt
          source venv_cv32e20-dv/bin/activate

      - name: Set up RISC-V Toolchain
        run: |
          export CV_SW_TOOLCHAIN=/opt/riscv
          echo "Ensuring RISC-V toolchain is present at $CV_SW_TOOLCHAIN"
          if [ ! -f $CV_SW_TOOLCHAIN/bin/riscv32-corev-elf-gcc ]; then
            echo "Toolchain not found at $CV_SW_TOOLCHAIN/bin/riscv32-corev-elf-gcc. Please ensure it is installed on the host."
            exit 1
          fi

      - name: Run hello-world UVM test without ISS/Spike
        run: |
          export CV_SW_TOOLCHAIN=/opt/riscv
          set_questa_one_2025
          export SIMULATOR=vsim
          cd sim/uvmt/
          make clean_all
          make test TEST=hello-world USE_ISS=NO
